src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="date")
     */
    private $published_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $updated_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url_alias;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedDate(): ?\DateTimeInterface
    {
        return $this->published_date;
    }

    public function setPublishedDate(\DateTimeInterface $published_date): self
    {
        $this->published_date = $published_date;

        return $this;
    }

    public function getUpdatedDate(): ?\DateTimeInterface
    {
        return $this->updated_date;
    }

    public function setUpdatedDate(?\DateTimeInterface $updated_date): self
    {
        $this->updated_date = $updated_date;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUrlAlias(): ?string
    {
        return $this->url_alias;
    }

    public function setUrlAlias(string $url_alias): self
    {
        $this->url_alias = $url_alias;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
    public function __toString(){
        return $this->title;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use Doctrine\ORM\EntityManager;
use App\Repository\UserRepository;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class BlogController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(ArticleRepository $repo, Request $request): Response
    {

        $articles = $repo->findAll();
        return $this->render('blog/index.html.twig', [
            'articles' => $articles,
        ]);
    }
    /**
     * @Route("/articles", name="blog_articles")
     */
    public function articles(ArticleRepository $repo, Request $request): Response
    {
        $articles = $repo->findAll();
        return $this->render('blog/articles.html.twig',[
            'articles'=>$articles
        ]);
    }
    /**
     * @Route("/article/{id}", name="blog_article")
     */
    public function article(Article $article): Response
    {
        return $this->render('blog/article.html.twig',[
            'article'=>$article
        ]);
    }

    /**
     * @Security("is_granted('ROLE_USER')")
     * @Route("/post/publish", name="blog_article_publish")
     */
    public function publish(EntityManagerInterface $em, Request $request):Response
    {
        $user = $this->getUser();
        $article = new Article();
        $publishForm = $this->createForm( ArticleType::class, $article);
        $publishForm->handleRequest($request);

        if($publishForm->isSubmitted() && $publishForm->isValid()){
            $article->setAuthor($user);
            $article->setPublishedDate(new \DateTime());
            $article->setUpdatedDate(new \DateTime());
            $article->setUrlAlias(md5(uniqid(rand(), true)));
            $em->persist($article);
            $em->flush();
            return $this->redirectToRoute('blog_article', [
                'id' => $article->getId()
            ]);

        }
        return $this->render('blog/publish.html.twig',[
            'publishForm'=>$publishForm->createView()
        ]);

    }
    /**
     * @Security("is_granted('ROLE_USER')")
     * @Route("/article/edit/{id}", name="blog_article_edit")
     */
    public function edit(EntityManagerInterface $em, Request $request, Article $article):Response
    {
        $editForm = $this->createForm(ArticleType::class, $article);
        $editForm->handleRequest($request);

        if($editForm->isSubmitted() && $editForm->isValid()){

            $article->setUpdatedDate(new \DateTime());
            $em->persist($article);
            $em->flush();

            return $this->redirectToRoute('blog_article', [
                'id' => $article->getId()
            ]);

        }
        return $this->render('blog/edit.html.twig',[
            'editForm'=>$editForm->createView()
        ]);

    }
    /**
     * @Security("is_granted('ROLE_USER')")
     * @Route("/article/delete/{id}", name="blog_article_delete")
     */
    public function delete(EntityManagerInterface $em, Request $request, Article $article):Response
    {
        $em->remove($article);
        $em->flush();
        return $this->redirectToRoute('profile');
    }

    /**
     * @Security("is_granted('ROLE_USER')")
     * @Route("/profile", name="profile")
     */
    public function profile(EntityManagerInterface $em, Request $request, ArticleRepository $repo, UserInterface $user):Response
    {
        $articles = $user->getArticles();
        return $this->render('blog/profile.html.twig', [
            'articles'=>$articles
            ]);   
    }
}

templates/blog/article.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	{{article.title}}
{% endblock %}

{% block body %}

	<!--Main layout-->
	<main class="mt-5 pt-4">
		<div
			class="container dark-grey-text mt-5">
			<!--Grid row-->
			<div
				class="row wow fadeIn">
				<!--Grid column-->
				<div class="col-md-6 mb-4">
					<img src="{{ article.image }}" class="img-fluid" alt=""/>
				</div>
				<!--Grid column-->

				<!--Grid column-->
				<div
					class="col-md-6 mb-4">
					<!--Content-->
					<div class="p-4">
						<div class="mb-3">
							<a href="">
								<span class="badge purple mr-1">Catégorie:
									{{ article.category }}</span>
							</a>
						</div>
						<p class="lead">
							<span class="lead font-weight-bold mr-1">
								{{ article.title }}
							</span>
						</p>
						<div class="ml-md-auto mr-md-0 d-md-flex">
							Créé le :
							{{ article.publishedDate | date("d/m/Y", "Europe/Paris") }}
							| mis à jour le :
							{{ article.updatedDate | date("d/m/Y", "Europe/Paris")}}
						</div>
						<p class="lead font-weight-bold">Description</p>

						<p>
							{{ article.content }}
						</p>

						<form
							class="d-flex justify-content-left"><!-- Default input -->
						</form>
					</div>
					<!--Content-->
				</div>
				<!--Grid column-->
			</div>
			<!--Grid row-->

			<hr/>
		</div>
	</main>
{% endblock %}

templates/blog/articles.html.twig
{% extends 'base.html.twig' %}
{% block title %}Articles
{% endblock %}


{% block body %}


	<div class="album py-5 bg-light">
		<div class="container">
			<h2>Articles</h2>

			<div class="Articles">

				<hr/>


				<div class="row">
					{% for article in articles %}
						<div class="col-md-4">
							<div class="card mb-4 box-shadow" style="height: 100%">
								<img class="card-img-top" src="{{ article.image }}" alt="Card image cap" height="300rem"/>
								<div class="card-body text-center">
									<h5 class="card-title">
										{{ article.title }}
									</h5>
									<div class="ml-md-auto mr-md-0 d-md-flex">
										Créé le :
										{{ article.publishedDate | date("d/m/Y", "Europe/Paris") }}
										| mis à jour le :
										{{ article.updatedDate | date("d/m/Y", "Europe/Paris")}}
									</div>

									<div class="row"></div>

									<button type="button" class="btn btn-dark btn-lg btn-block">
										<a href="{{path('blog_article',{'id':article.id})}}">Lire la suite ...</a>
									</button>
								</div>

							</div>

						</div>
					{% endfor %}
				</div>

			</div>

		</div>
	</div>


{% endblock %}

templates/blog/edit.html.twig
{% extends "base.html.twig" %}
{% block title %}Editer un article
{% endblock %}
{% form_theme editForm 'bootstrap_4_layout.html.twig' %}
{% block body %}
	<div>
		{{form_start(editForm)}}


		{{form_row(editForm.title, {'attr':{
    'placeholder' : "Titre de l'article"}}) }}
		{{form_row(editForm.category) }}
		{{form_row(editForm.content, {'attr':{
    'placeholder':" Contenu de l'article"}}) }}
		{{form_row(editForm.image, {'attr':{
    'placeholder':"Url de l'image"}}) }}


		<button type="submit" class="btn bnt-success">
			Modifier
		</button>
		{{ form_end(editForm) }}
	</div>
{% endblock %}

templates/blog/index.html.twig
{% extends "base.html.twig" %}
{% block body %}
	<section class="py-5 text-center container" style="background: url(''); background-size: cover; background-position: center top;">
		<div class="row py-lg-5">
			<div class="col-lg-6 col-md-8 mx-auto">
				<h1 class="fw-light">Bonjour !</h1>
				<p class="lead">Bienvenue sur mon blog.</p>
			</div>
		</div>
	</section>

	<!--Carousel Wrapper-->
	<div
		id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel">

		<!--Controls-->
		<div class="controls-top">
			<a class="btn-floating" href="#multi-item-example" data-slide="prev">
				<i class="fas fa-chevron-left"></i>
			</a>
			<a class="btn-floating" href="#multi-item-example" data-slide="next">
				<i class="fas fa-chevron-right"></i>
			</a>
		</div>
		<!--/.Controls-->

		<!--Indicators-->
		<ol class="carousel-indicators">
			<li data-target="#multi-item-example" data-slide-to="0" class="active"></li>
			<li data-target="#multi-item-example" data-slide-to="1"></li>

		</ol>
		<!--/.Indicators-->

		<!--Slides-->
		<div
			class="carousel-inner" role="listbox">

			<!--First slide-->
			{% for article in articles %}


				<div class="carousel-item active">

					<div class="col-md-3" style="float:left">
						<div class="card mb-2">
							<img class="card-img-top" src="{{article.image}}" alt="Card image cap">
							<div class="card-body">
								<h4 class="card-title">{{article.title}}</h4>
								<p class="card-text">{{article.category}}</p>
								<div class="ml-md-auto mr-md-0 d-md-flex">
									Créé le :
									{{ article.publishedDate | date("d/m/Y", "Europe/Paris") }}
									| mis à jour le :
									{{ article.updatedDate | date("d/m/Y", "Europe/Paris")}}
								</div>
								<a class="btn btn-primary" href="{{path('blog_article',{'id':article.id})}}">Lire</a>
							</div>
						</div>
					</div>
				{% endfor %}


			</div>
			<!--/.Slides-->

		</div>
		<!--/.Carousel Wrapper-->
	{% endblock %}

templates/blog/profile.html.twig
{% extends 'base.html.twig' %}
{% block title %}Mes articles
{% endblock %}


{% block body %}


	<div class="album py-5 bg-light">
		<div class="container">
			<h2>Mes articles</h2>

			<div class="Articles">

				<hr/>


				<div class="row">
					{% for article in articles %}
						<div class="col-md-4">
							<div class="card mb-4 box-shadow" style="height: 100%">
								<img class="card-img-top" src="{{ article.image }}" alt="Card image cap" height="300rem"/>
								<div class="card-body text-center">
									<h5 class="card-title">
										{{ article.title }}
									</h5>
									<div class="ml-md-auto mr-md-0 d-md-flex">
										Créé le :
										{{ article.publishedDate | date("d/m/Y", "Europe/Paris") }}
										| mis à jour le :
										{{ article.updatedDate | date("d/m/Y", "Europe/Paris")}}
									</div>

									<div class="row"></div>

									<button type="button" class="btn btn-dark btn-lg btn-block">
										<a href="{{path('blog_article',{'id':article.id})}}">Lire la suite ...</a>
									</button>
									<button type="button" class="btn btn-dark btn-lg btn-block">
										<a href="{{path('blog_article_edit',{'id':article.id})}}">Editer</a>
									</button>
									<button type="button" class="btn btn-dark btn-lg btn-block">
										<a href="{{path('blog_article_delete',{'id':article.id})}}">Supprimer</a>
									</button>
								</div>

							</div>

						</div>
					{% endfor %}
				</div>

			</div>

		</div>
	</div>


{% endblock %}

templates/blog/publish.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un article
{% endblock %}
{# ... #}
{# this tag only applies to the forms defined in this template #}
{% form_theme publishForm 'bootstrap_4_layout.html.twig' %}
{% block body %}
	<h1 style="text-align:center">
		Publier un article
	</h1>

	{{form_start(publishForm)}}


	{{form_row(publishForm.title, {'attr':{
    'placeholder' : "Titre de l'article"}}) }}
	{{form_row(publishForm.category) }}
	{{form_row(publishForm.content, {'attr':{
    'placeholder':" Contenu de l'article"}}) }}
	{{form_row(publishForm.image, {'attr':{
    'placeholder':"Url de l'image"}}) }}


	<button type="submit" class="btn bnt-success">
		Publier
	</button>

	{{form_end(publishForm)}}
{% endblock %}